### ISSUE TITLE
De bro wordt niet meer als xml ondersteund

### ISSUE THREAD

**Issue by ArnaudYK** [rivm-syso/OURS#6]
De BRO was tot voorkort als xml bestand te downloaden. Dat is niet meer het geval. Momenteel wordt het format geopackage ondersteund. Deze wordt dagelijks geactualiseerd (ipv wekelijks bij de xml). OURS ondersteunt momenteel het geopackage formaat niet. Hier wordt aan gewerkt.

**Comment by csmulders** [comment]
Is hier al een update over?

**Comment by ArnaudYK** [comment]
Helaas is er nog geen update beschikbaar. Ik hoop dat daar de komende weken tijd voor is. We wilden dit met een algemene update van het model aanbieden.

**Comment by csmulders** [comment]
Heb je dan toevallig nog een oude versie van het brocpt.xml bestand? Dan kunnen wij er nog wel mee verder ondanks dat we dan niet alle sonderingen hebben.

**Comment by ArnaudYK** [comment]
DE BRO tool zal in januari 2022 worden aangepast. In februari 2022 volgt een nieuwe release

**Comment by ArnaudYK** [comment]
Nieuwe release in uitgebracht. Issue is opgelost
